package com.fenast.app.ibextube.db.model.resource;

import java.util.Date;
import javax.persistence.*;

/**
 * MovieTags generated by hbm2java
 */
/**
 * MovieTags generated by hbm2java
 */
@Entity
@Table(name = "movie_tags", catalog = "ibextube")
public class MovieTags implements java.io.Serializable {

    private int idmovieTags;
    private Movies movies;
    private Tags tags;
    private Date insDate;
    private Date lastUpdated;

    public MovieTags() {
    }

    public MovieTags(int idmovieTags, Movies movies, Tags tags) {
        this.idmovieTags = idmovieTags;
        this.movies = movies;
        this.tags = tags;
    }


    @Id

    @Column(name = "idmovie_tags", unique = true, nullable = false)
    public int getIdmovieTags() {
        return this.idmovieTags;
    }

    public void setIdmovieTags(int idmovieTags) {
        this.idmovieTags = idmovieTags;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "movies_movie_id", nullable = false)
    public Movies getMovies() {
        return this.movies;
    }

    public void setMovies(Movies movies) {
        this.movies = movies;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tags_tag_id", nullable = false)
    public Tags getTags() {
        return this.tags;
    }

    public void setTags(Tags tags) {
        this.tags = tags;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ins_date", length = 19)
    public Date getInsDate() {
        return this.insDate;
    }

    public void setInsDate(Date insDate) {
        this.insDate = insDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_updated", length = 19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

}