package com.fenast.app.ibextube.db.model.resource;// default package
// Generated Mar 30, 2018 10:22:26 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovieArtist generated by hbm2java
 */
@Entity
@Table(name = "movie_artist", catalog = "ibextube")
public class MovieArtist implements java.io.Serializable {

	private int idMovieArtist;
	private Artist artist;
	private Movies movies;
	private Date insDate;
	private Date lastUpdated;

	public MovieArtist() {
	}

	public MovieArtist(int idMovieArtist, Artist artist, Movies movies) {
		this.idMovieArtist = idMovieArtist;
		this.artist = artist;
		this.movies = movies;
	}

	@Id
	@Column(name = "idMOVIE_ARTIST", unique = true, nullable = false)
	public int getIdMovieArtist() {
		return this.idMovieArtist;
	}

	public void setIdMovieArtist(int idMovieArtist) {
		this.idMovieArtist = idMovieArtist;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "artist_id", nullable = false)
	public Artist getArtist() {
		return this.artist;
	}

	public void setArtist(Artist artist) {
		this.artist = artist;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "movie_id", nullable = false)
	public Movies getMovies() {
		return this.movies;
	}

	public void setMovies(Movies movies) {
		this.movies = movies;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ins_date", length = 19)
	public Date getInsDate() {
		return this.insDate;
	}

	public void setInsDate(Date insDate) {
		this.insDate = insDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
