package com.fenast.app.ibextube.db.model.resource;// default package
// Generated Mar 30, 2018 10:22:26 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SocialMedia generated by hbm2java
 */
@Entity
@Table(name = "social_media", catalog = "ibextube")
public class SocialMedia implements java.io.Serializable {

	private int socialMediaId;
	private String name;
	private Date insDate;
	private Date lastUpdated;

	public SocialMedia() {
	}

	public SocialMedia(int socialMediaId) {
		this.socialMediaId = socialMediaId;
	}

	public SocialMedia(int socialMediaId, String name) {
		this.socialMediaId = socialMediaId;
		this.name = name;
	}

	@Id

	@Column(name = "social_media_id", unique = true, nullable = false)
	public int getSocialMediaId() {
		return this.socialMediaId;
	}

	public void setSocialMediaId(int socialMediaId) {
		this.socialMediaId = socialMediaId;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ins_date", length = 19)
	public Date getInsDate() {
		return this.insDate;
	}

	public void setInsDate(Date insDate) {
		this.insDate = insDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
