package com.fenast.app.ibextube.db.model.resource;// default package
// Generated Mar 30, 2018 10:22:26 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SocialMediaArtist generated by hbm2java
 */
@Entity
@Table(name = "social_media_artist", catalog = "ibextube")
public class SocialMediaArtist implements java.io.Serializable {

	private int idsocialMediaArtist;
	private Artist artist;
	private SocialMedia socialMedia;
	private String url;
	private Date insDate;
	private Date lastUpdated;

	public SocialMediaArtist() {
	}

	public SocialMediaArtist(int idsocialMediaArtist, Artist artist, SocialMedia socialMedia) {
		this.idsocialMediaArtist = idsocialMediaArtist;
		this.artist = artist;
		this.socialMedia = socialMedia;
	}

	public SocialMediaArtist(int idsocialMediaArtist, Artist artist, SocialMedia socialMedia, String url) {
		this.idsocialMediaArtist = idsocialMediaArtist;
		this.artist = artist;
		this.socialMedia = socialMedia;
		this.url = url;
	}

	@Id

	@Column(name = "idsocial_media_artist", unique = true, nullable = false)
	public int getIdsocialMediaArtist() {
		return this.idsocialMediaArtist;
	}

	public void setIdsocialMediaArtist(int idsocialMediaArtist) {
		this.idsocialMediaArtist = idsocialMediaArtist;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "artist_id", nullable = false)
	public Artist getArtist() {
		return this.artist;
	}

	public void setArtist(Artist artist) {
		this.artist = artist;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "social_media_social_media_id", nullable = false)
	public SocialMedia getSocialMedia() {
		return this.socialMedia;
	}

	public void setSocialMedia(SocialMedia socialMedia) {
		this.socialMedia = socialMedia;
	}

	@Column(name = "url", length = 150)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ins_date", length = 19)
	public Date getInsDate() {
		return this.insDate;
	}

	public void setInsDate(Date insDate) {
		this.insDate = insDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
