package com.fenast.app.ibextube.db.model.resource;// default package
// Generated Mar 30, 2018 10:22:26 PM by Hibernate Tools 5.2.8.Final

import com.fenast.app.ibextube.http.ResponseMessage;

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * UserDetail generated by hbm2java
 */
@Entity
@Table(name = "userDetail", catalog = "ibextube")
@SequenceGenerator(name = "userSeq", initialValue = 1, allocationSize = 100)
public class UserDetail extends ResponseMessage implements java.io.Serializable  {

	private int idUser;
	private String username;
	private String password;
	private String firstName;
	private String lastName;
	private Date insDate;
	private Date lastUpdated;
	private String profilePic;

	public UserDetail() {
	}

	public UserDetail(int idUser) {
		this.idUser = idUser;
	}

	public UserDetail(int idUser, String username, String password ,String firstName, String lastName) {
		this.idUser = idUser;
		this.username = username;
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
	}

	@Id
/*	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "userSeq" )*/
	@NotNull
	@Column(name = "idUSER", unique = true, nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "username", length = 45)
	@NotNull
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "first_name", length = 45)
	@NotNull
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ins_date", length = 19)
	public Date getInsDate() {
		return this.insDate;
	}

	public void setInsDate(Date insDate) {
		this.insDate = insDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "profile_pic")
	public String getProfilePic() {
		return profilePic;
	}

	public void setProfilePic(String profilePic) {
		this.profilePic = profilePic;
	}

	@Transient
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Override
	public String toString() {
		return "UserDetail{" +
				"idUser=" + idUser +
				", username='" + username + '\'' +
				", firstName='" + firstName + '\'' +
				", lastName='" + lastName + '\'' +
				", insDate=" + insDate +
				", lastUpdated=" + lastUpdated +
				'}';
	}
}
