security:
    oauth2:
        client:
            access-token-uri: https://dev-686865.oktapreview.com/oauth2/default/v1/token
            userDetail-authorization-uri: https://dev-686865.oktapreview.com/oauth2/default/v1/authorize
            client-id: 0oaem06ruwIoFLeuN0h7
            scope: openid profile email
        resource:
            userDetail-info-uri: https://dev-686865.oktapreview.com/oauth2/default/v1/userinfo
            token-info-uri: https://dev-686865.oktapreview.com/oauth2/default/v1/introspect
            prefer-token-info: false