package com.fenast.app.ibextube.db.model.movie;// default package
// Generated Feb 23, 2018 11:30:17 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MovieRating generated by hbm2java
 */
@Entity
@Table(name = "movie_rating", catalog = "ibextube")
public class MovieRating implements java.io.Serializable {

	private MovieRatingId id;
	private Movies movies;
	private User user;
	private Double rating;
	private String ratingDate;

	public MovieRating() {
	}

	public MovieRating(MovieRatingId id, Movies movies, User user) {
		this.id = id;
		this.movies = movies;
		this.user = user;
	}

	public MovieRating(MovieRatingId id, Movies movies, User user, Double rating, String ratingDate) {
		this.id = id;
		this.movies = movies;
		this.user = user;
		this.rating = rating;
		this.ratingDate = ratingDate;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idRating", column = @Column(name = "idRATING", nullable = false)),
			@AttributeOverride(name = "movieId", column = @Column(name = "movie_id", nullable = false)),
			@AttributeOverride(name = "userIdUser", column = @Column(name = "USER_idUSER", nullable = false)) })
	public MovieRatingId getId() {
		return this.id;
	}

	public void setId(MovieRatingId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "movie_id", nullable = false, insertable = false, updatable = false)
	public Movies getMovies() {
		return this.movies;
	}

	public void setMovies(Movies movies) {
		this.movies = movies;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_idUSER", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "rating", precision = 22, scale = 0)
	public Double getRating() {
		return this.rating;
	}

	public void setRating(Double rating) {
		this.rating = rating;
	}

	@Column(name = "rating_date", length = 45)
	public String getRatingDate() {
		return this.ratingDate;
	}

	public void setRatingDate(String ratingDate) {
		this.ratingDate = ratingDate;
	}

}
