package com.fenast.app.ibextube.db.model.movie;// default package
// Generated Feb 23, 2018 11:30:17 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Photo generated by hbm2java
 */
@Entity
@Table(name = "photo", catalog = "ibextube")
public class Photo implements java.io.Serializable {

	private int photoId;
	private String photoName;
	private String url;
	private Set<Movies> movieses = new HashSet<Movies>(0);
	private Set<Artist> artists = new HashSet<Artist>(0);

	public Photo() {
	}

	public Photo(int photoId) {
		this.photoId = photoId;
	}

	public Photo(int photoId, String photoName, String url, Set<Movies> movieses, Set<Artist> artists) {
		this.photoId = photoId;
		this.photoName = photoName;
		this.url = url;
		this.movieses = movieses;
		this.artists = artists;
	}

	@Id

	@Column(name = "photo_id", unique = true, nullable = false)
	public int getPhotoId() {
		return this.photoId;
	}

	public void setPhotoId(int photoId) {
		this.photoId = photoId;
	}

	@Column(name = "photo_name", length = 45)
	public String getPhotoName() {
		return this.photoName;
	}

	public void setPhotoName(String photoName) {
		this.photoName = photoName;
	}

	@Column(name = "url", length = 45)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "photo")
	public Set<Movies> getMovieses() {
		return this.movieses;
	}

	public void setMovieses(Set<Movies> movieses) {
		this.movieses = movieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "photo")
	public Set<Artist> getArtists() {
		return this.artists;
	}

	public void setArtists(Set<Artist> artists) {
		this.artists = artists;
	}

}
