package com.fenast.app.ibextube.db.model.movie;// default package
// Generated Feb 23, 2018 11:30:17 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tags generated by hbm2java
 */
@Entity
@Table(name = "tags", catalog = "ibextube")
public class Tags implements java.io.Serializable {

	private int tagId;
	private String value;
	private Set<MovieTags> movieTagses = new HashSet<MovieTags>(0);

	public Tags() {
	}

	public Tags(int tagId) {
		this.tagId = tagId;
	}

	public Tags(int tagId, String value, Set<MovieTags> movieTagses) {
		this.tagId = tagId;
		this.value = value;
		this.movieTagses = movieTagses;
	}

	@Id

	@Column(name = "tag_id", unique = true, nullable = false)
	public int getTagId() {
		return this.tagId;
	}

	public void setTagId(int tagId) {
		this.tagId = tagId;
	}

	@Column(name = "value", length = 45)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tags")
	public Set<MovieTags> getMovieTagses() {
		return this.movieTagses;
	}

	public void setMovieTagses(Set<MovieTags> movieTagses) {
		this.movieTagses = movieTagses;
	}

}
