package com.fenast.app.ibextube.db.model.movie;// default package
// Generated Feb 23, 2018 11:30:17 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "ibextube")
public class User implements java.io.Serializable {

	private int idUser;
	private Set<MovieRating> movieRatings = new HashSet<MovieRating>(0);

	public User() {
	}

	public User(int idUser) {
		this.idUser = idUser;
	}

	public User(int idUser, Set<MovieRating> movieRatings) {
		this.idUser = idUser;
		this.movieRatings = movieRatings;
	}

	@Id

	@Column(name = "idUSER", unique = true, nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<MovieRating> getMovieRatings() {
		return this.movieRatings;
	}

	public void setMovieRatings(Set<MovieRating> movieRatings) {
		this.movieRatings = movieRatings;
	}

}
