package com.fenast.app.ibextube.db.model;// default package
// Generated Mar 30, 2018 10:22:26 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Artist generated by hbm2java
 */
@Entity
@Table(name = "artist", catalog = "ibextube")
public class Artist implements java.io.Serializable {

	private int id;
	private Photo photo;
	private String firstName;
	private String lastName;
	private Character gender;
	private Date insDate;
	private Date lastUpdated;
	private Set<SocialMediaArtist> socialMediaArtists = new HashSet<SocialMediaArtist>(0);
	private Set<MovieArtist> movieArtists = new HashSet<MovieArtist>(0);

	public Artist() {
	}

	public Artist(int id, Photo photo) {
		this.id = id;
		this.photo = photo;
	}

	public Artist(int id, Photo photo, String firstName, String lastName, Character gender,
				  Set<SocialMediaArtist> socialMediaArtists, Set<MovieArtist> movieArtists) {
		this.id = id;
		this.photo = photo;
		this.firstName = firstName;
		this.lastName = lastName;
		this.gender = gender;
		this.socialMediaArtists = socialMediaArtists;
		this.movieArtists = movieArtists;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PHOTO_photo_id", nullable = false)
	public Photo getPhoto() {
		return this.photo;
	}

	public void setPhoto(Photo photo) {
		this.photo = photo;
	}

	@Column(name = "first_name", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "gender", length = 1)
	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ins_date", length = 19)
	public Date getInsDate() {
		return this.insDate;
	}

	public void setInsDate(Date insDate) {
		this.insDate = insDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "artist")
	public Set<SocialMediaArtist> getSocialMediaArtists() {
		return this.socialMediaArtists;
	}

	public void setSocialMediaArtists(Set<SocialMediaArtist> socialMediaArtists) {
		this.socialMediaArtists = socialMediaArtists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "artist")
	public Set<MovieArtist> getMovieArtists() {
		return this.movieArtists;
	}

	public void setMovieArtists(Set<MovieArtist> movieArtists) {
		this.movieArtists = movieArtists;
	}

}
