package com.fenast.app.ibextube.db.model;// default package
// Generated Mar 30, 2018 10:36:26 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MovieTagsId generated by hbm2java
 */
@Embeddable
public class MovieTagsId implements java.io.Serializable {

	private int movieId;
	private int tagId;

	public MovieTagsId() {
	}

	public MovieTagsId(int movieId, int tagId) {
		this.movieId = movieId;
		this.tagId = tagId;
	}

	@Column(name = "movie_id", nullable = false)
	public int getMovieId() {
		return this.movieId;
	}

	public void setMovieId(int movieId) {
		this.movieId = movieId;
	}

	@Column(name = "tag_id", nullable = false)
	public int getTagId() {
		return this.tagId;
	}

	public void setTagId(int tagId) {
		this.tagId = tagId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MovieTagsId))
			return false;
		MovieTagsId castOther = (MovieTagsId) other;

		return (this.getMovieId() == castOther.getMovieId()) && (this.getTagId() == castOther.getTagId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMovieId();
		result = 37 * result + this.getTagId();
		return result;
	}

}
