package com.fenast.app.ibextube.db.model;// default package
// Generated Mar 29, 2018 9:00:37 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MovieArtist generated by hbm2java
 */
@Entity
@Table(name = "movie_artist", catalog = "ibextube")
public class MovieArtist implements java.io.Serializable {

	private int idMovieArtist;
	private Artist artist;
	private Movies movies;

	public MovieArtist() {
	}

	public MovieArtist(int idMovieArtist, Artist artist, Movies movies) {
		this.idMovieArtist = idMovieArtist;
		this.artist = artist;
		this.movies = movies;
	}

	@Id

	@Column(name = "idMOVIE_ARTIST", unique = true, nullable = false)
	public int getIdMovieArtist() {
		return this.idMovieArtist;
	}

	public void setIdMovieArtist(int idMovieArtist) {
		this.idMovieArtist = idMovieArtist;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "artist_id", nullable = false)
	public Artist getArtist() {
		return this.artist;
	}

	public void setArtist(Artist artist) {
		this.artist = artist;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "movie_id", nullable = false)
	public Movies getMovies() {
		return this.movies;
	}

	public void setMovies(Movies movies) {
		this.movies = movies;
	}

}
