package com.fenast.app.ibextube.db.model;

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovieTags generated by hbm2java
 */
@Entity
@Table(name = "movie-tags", catalog = "ibextube")
public class MovieTags implements java.io.Serializable {

    private MovieTagsId id;
    private Movies movies;
    private Tags tags;
    private Date insDate;
    private Date lastUpdated;

    public MovieTags() {
    }

    public MovieTags(MovieTagsId id, Movies movies, Tags tags) {
        this.id = id;
        this.movies = movies;
        this.tags = tags;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "movieId", column = @Column(name = "movie_id", nullable = false)),
            @AttributeOverride(name = "tagId", column = @Column(name = "tag_id", nullable = false)) })
    public MovieTagsId getId() {
        return this.id;
    }

    public void setId(MovieTagsId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "movie_id", nullable = false, insertable = false, updatable = false)
    public Movies getMovies() {
        return this.movies;
    }

    public void setMovies(Movies movies) {
        this.movies = movies;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tag_id", nullable = false, insertable = false, updatable = false)
    public Tags getTags() {
        return this.tags;
    }

    public void setTags(Tags tags) {
        this.tags = tags;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ins_date", length = 19)
    public Date getInsDate() {
        return this.insDate;
    }

    public void setInsDate(Date insDate) {
        this.insDate = insDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_updated", length = 19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

}
