package com.fenast.app.ibextube.db.model;// default package
// Generated Mar 29, 2018 9:00:37 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovieComment generated by hbm2java
 */
@Entity
@Table(name = "movie_comment", catalog = "ibextube")
public class MovieComment implements java.io.Serializable {

	private int commentId;
	private Movies movies;
	private User user;
	private String comment;
	private Date commentDate;

	public MovieComment() {
	}

	public MovieComment(int commentId, Movies movies, User user) {
		this.commentId = commentId;
		this.movies = movies;
		this.user = user;
	}

	public MovieComment(int commentId, Movies movies, User user, String comment, Date commentDate) {
		this.commentId = commentId;
		this.movies = movies;
		this.user = user;
		this.comment = comment;
		this.commentDate = commentDate;
	}

	@Id

	@Column(name = "comment_id", unique = true, nullable = false)
	public int getCommentId() {
		return this.commentId;
	}

	public void setCommentId(int commentId) {
		this.commentId = commentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MOVIES_movie_id", nullable = false)
	public Movies getMovies() {
		return this.movies;
	}

	public void setMovies(Movies movies) {
		this.movies = movies;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_idUSER", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "comment", length = 45)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "comment_date", length = 10)
	public Date getCommentDate() {
		return this.commentDate;
	}

	public void setCommentDate(Date commentDate) {
		this.commentDate = commentDate;
	}

}
