package com.fenast.app.ibextube.db.model;// default package
// Generated Mar 29, 2018 9:00:37 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MovieTags generated by hbm2java
 */
@Entity
@Table(name = "movie-tags", catalog = "ibextube")
public class MovieTags implements java.io.Serializable {

	private int movieTagId;
	private Movies movies;
	private Tags tags;

	public MovieTags() {
	}

	public MovieTags(int movieTagId, Movies movies, Tags tags) {
		this.movieTagId = movieTagId;
		this.movies = movies;
		this.tags = tags;
	}

	@Id

	@Column(name = "movie_tag_id", unique = true, nullable = false)
	public int getMovieTagId() {
		return this.movieTagId;
	}

	public void setMovieTagId(int movieTagId) {
		this.movieTagId = movieTagId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "movie_id", nullable = false)
	public Movies getMovies() {
		return this.movies;
	}

	public void setMovies(Movies movies) {
		this.movies = movies;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tag_id", nullable = false)
	public Tags getTags() {
		return this.tags;
	}

	public void setTags(Tags tags) {
		this.tags = tags;
	}

}
