package com.fenast.app.ibextube.db.model;// default package
// Generated Mar 30, 2018 10:22:26 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovieGenres generated by hbm2java
 */
@Entity
@Table(name = "movie_genres", catalog = "ibextube")
public class MovieGenres implements java.io.Serializable {

	private int movieGenereId;
	private Genre genre;
	private Movies movies;
	private Date insDate;
	private Date lastUpdated;

	public MovieGenres() {
	}

	public MovieGenres(int movieGenereId, Genre genre, Movies movies) {
		this.movieGenereId = movieGenereId;
		this.genre = genre;
		this.movies = movies;
	}

	@Id
	@Column(name = "movie_genere_id", unique = true, nullable = false)
	public int getMovieGenereId() {
		return this.movieGenereId;
	}

	public void setMovieGenereId(int movieGenereId) {
		this.movieGenereId = movieGenereId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "genre_id", nullable = false)
	public Genre getGenre() {
		return this.genre;
	}

	public void setGenre(Genre genre) {
		this.genre = genre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "movie_id", nullable = false)
	public Movies getMovies() {
		return this.movies;
	}

	public void setMovies(Movies movies) {
		this.movies = movies;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ins_date", length = 19)
	public Date getInsDate() {
		return this.insDate;
	}

	public void setInsDate(Date insDate) {
		this.insDate = insDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
