package com.fenast.app.ibextube.db.model;// default package
// Generated Feb 26, 2018 3:39:32 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovieRating generated by hbm2java
 */
@Entity
@Table(name = "movie_rating", catalog = "ibextube")
public class MovieRating implements java.io.Serializable {

	private int ratingId;
	private Double ratingPoint;
	private Integer totalRatingCount;
	private Date lastRated;
	private Set<Movies> movieses = new HashSet<Movies>(0);

	public MovieRating() {
	}

	public MovieRating(int ratingId) {
		this.ratingId = ratingId;
	}

	public MovieRating(int ratingId, Double ratingPoint, Integer totalRatingCount, Date lastRated,
			Set<Movies> movieses) {
		this.ratingId = ratingId;
		this.ratingPoint = ratingPoint;
		this.totalRatingCount = totalRatingCount;
		this.lastRated = lastRated;
		this.movieses = movieses;
	}

	@Id

	@Column(name = "rating_id", unique = true, nullable = false)
	public int getRatingId() {
		return this.ratingId;
	}

	public void setRatingId(int ratingId) {
		this.ratingId = ratingId;
	}

	@Column(name = "rating_point", precision = 22, scale = 0)
	public Double getRatingPoint() {
		return this.ratingPoint;
	}

	public void setRatingPoint(Double ratingPoint) {
		this.ratingPoint = ratingPoint;
	}

	@Column(name = "total_rating_count")
	public Integer getTotalRatingCount() {
		return this.totalRatingCount;
	}

	public void setTotalRatingCount(Integer totalRatingCount) {
		this.totalRatingCount = totalRatingCount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_rated", length = 10)
	public Date getLastRated() {
		return this.lastRated;
	}

	public void setLastRated(Date lastRated) {
		this.lastRated = lastRated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movieRating")
	public Set<Movies> getMovieses() {
		return this.movieses;
	}

	public void setMovieses(Set<Movies> movieses) {
		this.movieses = movieses;
	}

}
