package com.fenast.app.ibextube.db.model;// default package
// Generated Mar 30, 2018 10:22:26 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovieRating generated by hbm2java
 */
@Entity
@Table(name = "movie_rating", catalog = "ibextube")
public class MovieRating implements java.io.Serializable {

	private int ratingId;
	private Movies movies;
	private User user;
	private Double ratingPoint;
	private Integer totalRatingCount;
	private Date lastRated;
	private Date insDate;
	private Date lastUpdated;

	public MovieRating() {
	}

	public MovieRating(int ratingId, Movies movies, User user) {
		this.ratingId = ratingId;
		this.movies = movies;
		this.user = user;
	}

	public MovieRating(int ratingId, Movies movies, User user, Double ratingPoint, Integer totalRatingCount,
					   Date lastUpdated) {
		this.ratingId = ratingId;
		this.movies = movies;
		this.user = user;
		this.ratingPoint = ratingPoint;
		this.totalRatingCount = totalRatingCount;
		this.lastUpdated = lastUpdated;
	}

	@Id

	@Column(name = "rating_id", unique = true, nullable = false)
	public int getRatingId() {
		return this.ratingId;
	}

	public void setRatingId(int ratingId) {
		this.ratingId = ratingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "movies_movie_id", nullable = false)
	public Movies getMovies() {
		return this.movies;
	}

	public void setMovies(Movies movies) {
		this.movies = movies;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_idUSER", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "rating_point", precision = 22, scale = 0)
	public Double getRatingPoint() {
		return this.ratingPoint;
	}

	public void setRatingPoint(Double ratingPoint) {
		this.ratingPoint = ratingPoint;
	}

	@Column(name = "total_rating_count")
	public Integer getTotalRatingCount() {
		return this.totalRatingCount;
	}

	public void setTotalRatingCount(Integer totalRatingCount) {
		this.totalRatingCount = totalRatingCount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_rated", length = 10)
	public Date getLastRated() {
		return this.lastRated;
	}

	public void setLastRated(Date lastRated) {
		this.lastRated = lastRated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ins_date", length = 19)
	public Date getInsDate() {
		return this.insDate;
	}

	public void setInsDate(Date insDate) {
		this.insDate = insDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}

