package com.fenast.app.ibextube.db.model;// default package
// Generated Feb 26, 2018 3:39:32 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "ibextube")
public class User implements java.io.Serializable {

	private int idUser;
	private String username;
	private String password;
	private Set<MovieComment> movieComments = new HashSet<MovieComment>(0);

	public User() {
	}

	public User(int idUser) {
		this.idUser = idUser;
	}

	public User(int idUser, Set<MovieComment> movieComments) {
		this.idUser = idUser;
		this.movieComments = movieComments;
	}

	@Id

	@Column(name = "idUSER", unique = true, nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<MovieComment> getMovieComments() {
		return this.movieComments;
	}

	public void setMovieComments(Set<MovieComment> movieComments) {
		this.movieComments = movieComments;
	}

	@Column(name = "userName", nullable = false)
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
}
